# Generated by Django 5.0.6 on 2024-06-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_x_agent_descriptions_agent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
    ]
