# Generated by Django 5.0.6 on 2024-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='imags3.jpg', upload_to='property')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='#')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
