# Generated by Django 5.0.6 on 2024-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('statuse', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='property')),
                ('title', models.CharField(max_length=200)),
                ('rent', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('garages', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='property.category')),
            ],
        ),
    ]
